In [40]:
import numpy as np
 
K1 = np.array([[1],
             [-1]])

H1 = np.array([
       [1,0,0,0,1],
       [1,0,0,0,1],
       [1,1,1,1,1],
       [1,0,0,0,1],
       [1,0,0,0,1]])
 
def cov2(inputs,kernel,stride):
    inw,inh = inputs.shape
    w,h=kernel.shape
    outw = int((inw - w)/stride + 1)
    outh = int((inh - h)/stride + 1)
    arr = np.zeros(shape=(outw, outh))
    for g in range(outw):
        for t in range(outh):
            s = 0
            for i in range(w):
                for j in range(h):
                    s+=inputs[i+g*strde][j+t*strde]*f[i][j]
            arr[g][t]=s
    print(arr)
    return 0
 
cov2(H1,K1,1)

[[1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]


0

In [61]:
import numpy as np
 
K2 = np.array([[0,1],
             [1,0]])


X1 = np.array([
       [1,0,0,0,1],
       [0,1,0,1,0],
       [0,0,1,0,0],
       [0,1,0,1,0],
       [1,0,0,0,1]])
 
def cov2(inputs,kernel,stride):
    inw,inh = inputs.shape
    w,h=kernel.shape
    outw = int((inw - w)/stride + 1)
    outh = int((inh - h)/stride + 1)
    arr = np.zeros(shape=(outw, outh))
    for g in range(outw):
        for t in range(outh):
            s = 0
            for i in range(w):
                for j in range(h):
                    s+=inputs[i+g*stride][j+t*stride]*f[i][j]
            arr[g][t]=s
    print(arr)
    return 0
 
cov2(X1,K2,1)

[[0. 1. 0. 2.]
 [1. 0. 2. 0.]
 [0. 2. 0. 1.]
 [2. 0. 1. 0.]]


0

In [42]:
X1 = np.array([
       [1,0,0,0,1],
       [0,1,0,1,0],
       [0,0,1,0,0],
       [0,1,0,1,0],
       [1,0,0,0,1]])
 
X1_2d = np.pad(array=X1, pad_width=((0,1),(0,1)), mode='constant', constant_values=0)

K2 = np.array([[0,1],
             [1,0]])

 
def cov2(inputs,kernel,stride):
    inw,inh = inputs.shape
    w,h=kernel.shape
    outw = int((inw - w)/stride + 1)
    outh = int((inh - h)/stride + 1)
    arr = np.zeros(shape=(outw, outh))
    for g in range(outw):
        for t in range(outh):
            s = 0
            for i in range(w):
                for j in range(h):
                    s+=inputs[i+g*stride][j+t*stride]*f[i][j]
            arr[g][t]=s
    print(arr)
    return 0
 
cov2(X1_2d,K2,2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


0

In [51]:
import skimage.measure
skimage.measure.block_reduce(H1,(3,3), np.mean)

array([[0.55555556, 0.44444444],
       [0.22222222, 0.22222222]])

In [72]:
def pooling(inputMap,poolSize=3,poolStride=1,mode='mean'):
    """INPUTS:
              inputMap - input array of the pooling layer
              poolSize - X-size(equivalent to Y-size) of receptive field
              poolStride - the stride size between successive pooling squares
       
       OUTPUTS:
               outputMap - output array of the pooling layer
    """
    # inputMap sizes
    in_row,in_col = np.shape(inputMap)
    
    # outputMap sizes
    out_row,out_col = int(np.floor(in_row/poolSize)),int(np.floor(in_col/poolSize))
    row_remainder,col_remainder = np.mod(in_row,poolSize),np.mod(in_col,poolSize)
    if row_remainder != 0:
        out_row +=1
    if col_remainder != 0:
        out_col +=1
    outputMap = np.zeros((out_row,out_col))
    
    # padding
    temp_map = np.lib.pad(H1, ((0,3-row_remainder),(0,3-col_remainder)),  mode='constant', constant_values=0)
    
    # mean pooling
    for r_idx in range(0,out_row):
        for c_idx in range(0,out_col):
            startX = c_idx * poolSize
            startY = r_idx * poolSize
            poolField = temp_map[startY:startY + poolSize, startX:startX + poolSize]
            poolOut = np.mean(poolField)
            outputMap[r_idx,c_idx] = poolOut
    
    # retrun outputMap
    return  outputMap

pooling(H1,poolSize=3,poolStride=1,mode='mean')

array([[0.55555556, 0.44444444],
       [0.22222222, 0.22222222]])

In [83]:
def avg_pooling(z, pooling = (3, 3), strides=(1, 1), padding=(0, 0)):

    H, W = z.shape
    # zero padding
    padding_z = np.lib.pad(z, ((padding[0], padding[0]), (padding[1], padding[1])), mode = 'constant',constant_values=0)

    # the height and width of the output
    out_h = (H - pooling[0]) // strides[0] + 1
    out_w = (W - pooling[1]) // strides[1] + 1

    pool_z = np.zeros((out_h, out_w))

    for i in np.arange(out_h):
        for j in np.arange(out_w):
            pool_z[i, j] = np.mean(padding_z[strides[0] * i:strides[0] * i + pooling[0],strides[1] * j:strides[1] * j + pooling[1]])
    return pool_z

avg_pooling(H1, pooling, strides=(1, 1), padding=(0, 0))

array([[0.55555556, 0.33333333, 0.55555556],
       [0.55555556, 0.33333333, 0.55555556],
       [0.55555556, 0.33333333, 0.55555556]])

In [81]:
pooling = (3, 3)
strides=(1, 1)
H, W = H1.shape
out_h = (H - pooling[0]) // strides[0] + 1
out_w = (W - pooling[1]) // strides[1] + 1
out_h

3